name: schema_valid
description: Dart model validation with annotations and code generation
version: 0.0.1
repository: https://github.com/yuen-quinn/schema_valid

environment:
  sdk: ^3.2.3

dependencies:
  meta: ^1.18.2
  build: ^4.0.5
  source_gen: ^4.2.2

dev_dependencies:
  build_runner: ^2.13.1